### ISSUE TITLE
Coordinate issues

### ISSUE THREAD

**Issue by pythongod-exe** [crockwell/rel_pose#10]
Hello, thanks for your excellent work, I would like to ask why the habitat coordinate system is used when training on the matterport dataset and the predicted rotation is in the form of yzxw. If I want to use other datasets to train my code, can I place the pose as [x, y, z, qx, qy, qz, qw]?

**Comment by crockwell** [comment]
Hi -- the dataset containing renders on matterport is in habitat coordinates since it is collecting using habitat, i.e. habitat-matterport. As far as using for other datasets and the coordinate convention, I'd recommend you use [FAR](https://github.com/crockwell/far). It has about half the average error of this work along with indoor and outdoor checkpoints. I think the coordinate should be easier to work with as well!

**Comment by pythongod-exe** [comment]
Thanks for the suggestion, I will follow your suggestion to read another excellent work of yours！
